### PR TITLE
Added max_tokens alias to length in FinishReason

### PR DESCRIPTION
**Pull request by DuckyBlender**

### CODE REVIEW

**Comment by DuckyBlender** [comment]
yes i pushed 5 commits for one line change

**Comment by dongri** [comment]
@DuckyBlender Why was this added? Please explain the reason.

**Comment by DuckyBlender** [comment]
redundancy and openrouter Gemini api, feel free to close if it doesn't align with your preferences

**Comment by dongri** [comment]
See https://github.com/dongri/openai-api-rs/pull/137

**Pull request closed without merging**
