### PR TITLE
Support Proxy

### PR DESCRIPTION
**Pull request by supermoonie**

### CODE REVIEW

**Review by dongri — APPROVED** [review]
[LGTM](https://lgtm.lol/i/811)

**Comment by dongri** [comment]
https://crates.io/crates/openai-api-rs

**Comment by desprit** [comment]
Is it possible to use socks5 proxy somehow now? When I try it I get `unknown proxy scheme`, probably because
```
[dependencies.reqwest]
version = "0.12"
features = [
    "json",
    "multipart",
]
```
doesn't have `socks5` feature. But is there a way to override it on my side?

**Comment by dongri** [comment]
@desprit Fixed
https://github.com/dongri/openai-api-rs/pull/104/files
Please use v5.0.5

**Comment by desprit** [comment]
@dongri that was super fast, thank you very much!

**Pull request merged**
